import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./Components/nav";
import clsx, { ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className=" bg-black">
      
      <body className={inter.className}>{children} 
      <Script
          src={`//code.tidio.co/19m4tcrxxe3vnf0lsvntbbyadkwql9w8.js`}
          strategy="lazyOnload"
        />
        </body>
    </html>
  );
}
